name: Build an android release

on:
    push:
        tags:
          - 'release'

    workflow_dispatch:

permissions:
    contents: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        # - name: 'Checkout code'
        #   uses: 'actions/checkout@v2'

        # - name: 'Make envfile'
        #   env:
        #     GITHUB_CONTEXT: ${{ toJson(secrets) }}
        #   run: 'echo "$GITHUB_CONTEXT" > env.json && cat env.json'

        # - name: 'Set up JDK 11'
        #   uses: 'actions/setup-java@v2'
        #   with:
        #     distribution: 'zulu'
        #     java-version: '11'
        #     cache: 'gradle'
      
        # - name: 'Set up Flutter'
        #   uses: subosito/flutter-action@v2
        #   with:
        #     flutter-version: '3.7.7'
        #     channel: 'master'
        #     cache: true
      
        # - name: 'Check Flutter environment'
        #   run: 'flutter doctor -v'
      
        # - name: 'Get packages'
        #   run: 'flutter pub get'
      
        # # - name: 'Test'
        # #   run: flutter test

        # - name: 'Build APK'
        #   id: 'build'
        #   run: 'flutter build apk --release --dart-define-from-file=env.json'
        #   # Build the APK using the value of the "matrix-target" input.
        #   # Use the "id" property to give the step a unique identifier.
        #   # Use the "::set-output" command to set the value of the "built-apk" output variable.
      
        # # - name: 'Upload APK'
        # #   uses: 'actions/upload-artifact@v2'
        # #   with:
        # #     name: 'apk'
        # #     path: 'build/app/outputs/apk/release/'

        - name: 'Make envfile'
          env:
            GITHUB_CONTEXT: ${{ toJson(secrets) }}
          run: 'mkdir -p build/app/outputs/apk/release/ && echo "hui" > build/app/outputs/apk/release/file.apk'

        - name: 'Release the build'
          uses: ncipollo/release-action@v1
          with:
            name: 'Release - ${{github.event_name.head_commit.message}}'
            artifacts: 'build/app/outputs/apk/release/'