name: Build an android release

on:
    push:
        tags:
          - 'v*.*'

    workflow_dispatch:

permissions:
    contents: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        - name: 'Checkout code'
          uses: 'actions/checkout@v2'

        - name: 'Make envfile'
          env:
            GITHUB_CONTEXT: ${{ toJson(secrets) }}
          run: 'echo "$GITHUB_CONTEXT" > env.json && cat env.json'

        - name: 'Set up JDK 11'
          uses: 'actions/setup-java@v2'
          with:
            distribution: 'zulu'
            java-version: '11'
            cache: 'gradle'
      
        - name: 'Set up Flutter'
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.7.7'
            channel: 'master'
            cache: true
      
        - name: 'Check Flutter environment'
          run: 'flutter doctor -v'
      
        - name: 'Get packages'
          run: 'flutter pub get'
      
        - name: 'Test'    
          if: ${{ false }}
          run: flutter test

        - name: 'Build APK'
          id: 'build'
          run: 'flutter build apk --release --dart-define-from-file=env.json'

        - name: 'Make envfile'
          env:
            GITHUB_CONTEXT: ${{ toJson(secrets) }}
          run: 'mkdir -p build/app/outputs/apk/release/ && echo "hui" > build/app/outputs/apk/release/file.apk'

        - name: 'Release the build'
          uses: ncipollo/release-action@v1
          with:
            name: 'Release - ${{github.ref_name}}'
            artifacts: 'build/app/outputs/apk/release/*'